spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=projetesprit

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
